# Generated by Django 4.0.6 on 2022-09-09 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.TextField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NomeTarefa', models.TextField(max_length=100)),
                ('DescricaoTarefa', models.TextField()),
                ('DataInicio', models.DateField(auto_now_add=True)),
                ('Status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BackEnd.categoria')),
            ],
        ),
    ]
